on:
  push:
    branches:
      - main # Запускаем при пушах в ветку main
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Automatically merge on successful testing
      if: success()
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout main
        git fetch origin +refs/pull/*:refs/remotes/development/pr/*
        git merge --ff-only refs/remotes/development/pr/${{ github.event.pull_request.number }}
        git push origin main
